FROM nginx:alpine
RUN apk update && apk add bash
WORKDIR /
COPY . .
COPY nginx.conf /etc/nginx/nginx.conf
#COPY nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
#COPY . .
COPY entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh
ENTRYPOINT ["/bin/bash","/usr/local/bin/entrypoint.sh"]

#CMD ["/usr/sbin/nginx", "-g", "daemon off;"]

