FROM postgres:16

# Install pg_cron
RUN apt-get update && apt-get install -y postgresql-16-cron

# Add postgresql.conf configuration to load pg_cron
RUN echo "shared_preload_libraries = 'pg_cron'" >> /usr/share/postgresql/postgresql.conf.sample
RUN echo "cron.database_name = 'project_hud_db'" >> /usr/share/postgresql/postgresql.conf.sample

# Add initialization script
COPY init-db /docker-entrypoint-initdb.d/
